spring.datasource.url=jdbc:mysql://mysql-a7a1781-ehotelmirnes-mysql.l.aivencloud.com:10812/defaultdb?sslMode=REQUIRED
spring.datasource.username=${PROD_DB_USERNAME}
spring.datasource.password=${PROD_DB_PASSWORD}
